'use client';
import { useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, ChevronRight, Copy, CreditCard, KeyRound, Menu, MessageCircle, Package, ShoppingCart, X, Zap } from 'lucide-react';

const products = [
 {name:'Lifesteal Rank',price:199,category:'ranks',badge:'POPULAR',icon:'⚔️',desc:'Powerful perks for your next adventure.'},
 {name:'Champion Rank',price:399,category:'ranks',badge:'BEST VALUE',icon:'👑',desc:'Premium commands, cosmetics and perks.'},
 {name:'1000 Coins',price:99,category:'coins',badge:'COINS',icon:'💎',desc:'Spend coins on in-game goodies.'},
 {name:'5000 Coins',price:399,category:'coins',badge:'POPULAR',icon:'💰',desc:'A bigger balance for the Odaris economy.'},
 {name:'Warrior Bundle',price:599,category:'bundles',badge:'BUNDLE',icon:'🛡️',desc:'A complete starter bundle for warriors.'},
 {name:'Champion Bundle',price:899,category:'bundles',badge:'MEGA',icon:'🏆',desc:'Ranks, coins and bonus rewards together.'},
 {name:'Crate Key',price:39,category:'keys',badge:'KEY',icon:'🔑',desc:'Unlock a random crate reward.'},
 {name:'5x Crate Keys',price:149,category:'keys',badge:'5 KEYS',icon:'🗝️',desc:'Five chances to unlock rare rewards.'}
];
const tabs=[{id:'all',label:'ALL ITEMS',icon:Package},{id:'ranks',label:'RANKS',icon:Zap},{id:'coins',label:'COINS',icon:CreditCard},{id:'bundles',label:'BUNDLES',icon:ShoppingCart},{id:'keys',label:'KEYS',icon:KeyRound}];
export default function StorePage(){
 const [tab,setTab]=useState('all'),[cart,setCart]=useState<typeof products>([]),[menu,setMenu]=useState(false),[checkout,setCheckout]=useState(false),[copied,setCopied]=useState(false),[username,setUsername]=useState('');
 const visible=useMemo(()=>tab==='all'?products:products.filter(p=>p.category===tab),[tab]); const total=cart.reduce((s,p)=>s+p.price,0);
 const copyUpi=async()=>{await navigator.clipboard?.writeText('aaravg782013@fam');setCopied(true);setTimeout(()=>setCopied(false),1500)};
 return <main className="store-page">
 <header className="site-header"><a href="/" className="brand"><span className="brand-cube">◆</span> ODARIS <b>MC</b><small>OFFICIAL MINECRAFT STORE</small></a><nav className="desktop-nav"><a href="/">HOME</a><a className="active" href="/store">STORE</a><a href="/#why">ABOUT</a><a href="https://discord.gg/6ERJ8t7FtX">DISCORD</a></nav><div className="header-actions"><a className="google-button" href="/api/auth/google"><span>G</span> SIGN IN WITH GOOGLE</a><button className="cart-button" onClick={()=>setCheckout(true)}>CART <strong>{cart.length}</strong><ShoppingCart size={18}/></button><button className="menu-button" onClick={()=>setMenu(true)}><Menu/></button></div></header>
 {menu&&<div className="drawer-backdrop" onClick={()=>setMenu(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><span>ODARIS MC</span><button onClick={()=>setMenu(false)}><X/></button></div>{[['HOME','/'],['STORE','/store'],['ABOUT ODARIS MC','/#why'],['DISCORD COMMUNITY','https://discord.gg/6ERJ8t7FtX'],['TERMS & RULES','/terms'],['FREQUENTLY ASKED QUESTIONS','/faq'],['ADMIN CONSOLE','/admin']].map(([n,h])=><a key={n} href={h}>{n}</a>)}<div className="drawer-sign"><a href="/api/auth/google">G&nbsp; PLAYER LOGIN / SIGN IN</a></div></aside></div>}
 <section className="store-hero"><div className="ambient one"/><div className="ambient two"/><div className="store-hero-inner"><a className="back" href="/"><ArrowLeft size={16}/> BACK TO HOME</a><div className="store-pill">🛍️ OFFICIAL SERVER STORE</div><h1>SUPPORT THE<br/><em>SERVER</em> & UNLOCK<br/><i>REWARDS.</i></h1><p>Every purchase supports server development and community events.</p><div className="store-benefits"><span><Zap/> INSTANT DELIVERY</span><span><CheckCircle2/> SECURE CHECKOUT</span><span><MessageCircle/> DISCORD SUPPORT</span></div></div></section>
 <section className="catalog"><div className="catalog-head"><div><span className="eyebrow">ODARIS MC STORE</span><h2>CHOOSE YOUR <em>UPGRADE.</em></h2></div><p>Java & Bedrock • <b>zerithmc67.mcsh.io</b></p></div><div className="tabs">{tabs.map(({id,label,icon:Icon})=><button key={id} className={tab===id?'selected':''} onClick={()=>setTab(id)}><Icon size={18}/>{label}</button>)}</div><div className="product-grid">{visible.map(p=><article className="store-card" key={p.name}><div className="store-card-art">{p.icon}</div><span className="card-badge">{p.badge}</span><h3>{p.name}</h3><p>{p.desc}</p><div className="price-row"><strong>₹{p.price}</strong><button onClick={()=>setCart(c=>[...c,p])}>ADD <ShoppingCart size={15}/></button></div></article>)}</div></section>
 <section className="payment-info"><div className="payment-copy"><span className="eyebrow">PAYMENT & SUPPORT</span><h2>CHECKOUT <em>YOUR WAY.</em></h2><p>At checkout, open a ticket in Discord to complete your order, or pay using the displayed UPI details.</p><div className="pay-actions"><a href="https://discord.gg/6ERJ8t7FtX" className="discord-button"><MessageCircle/> OPEN DISCORD TICKET</a><button className="upi-button" onClick={copyUpi}>{copied?<CheckCircle2/>:<Copy/>} {copied?'UPI COPIED':'COPY UPI ID'}</button></div><code>aaravg782013@fam</code></div><div className="qr-card"><div className="qr-title">SCAN TO PAY</div><img src="https://api.qrserver.com/v1/create-qr-code/?size=260x260&margin=10&data=upi%3A%2F%2Fpay%3Fpa%3Daaravg782013%40fam%26pn%3DOdaris%2520MC%26cu%3DINR" alt="Odaris MC UPI payment QR"/><small>UPI ID: aaravg782013@fam</small></div></section>
 {checkout&&<div className="checkout-overlay" onClick={()=>setCheckout(false)}><section className="checkout-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setCheckout(false)}><X/></button><span className="eyebrow">SECURE ORDER</span><h2>YOUR <em>CART.</em></h2>{cart.length===0?<p className="empty">Your cart is empty. Add a rank, coins, bundle or key first.</p>:<><label>MINECRAFT USERNAME<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Your in-game username"/></label><div className="checkout-items">{cart.map((p,i)=><div key={i}><span>{p.name}</span><b>₹{p.price}</b></div>)}</div><div className="checkout-total"><span>TOTAL</span><strong>₹{total}</strong></div><a className="discord-button full" href="https://discord.gg/6ERJ8t7FtX">OPEN DISCORD TICKET TO PAY <ChevronRight/></a><p className="checkout-note">You can also pay by UPI using <b>aaravg782013@fam</b> or the QR. After payment, send your order details in the ticket.</p></>}</section></div>}
 <footer className="store-footer"><div className="brand"><span className="brand-cube">◆</span> ODARIS <b>MC</b></div><div><a href="/terms">TERMS & RULES</a><a href="/faq">FAQ</a><a href="https://discord.gg/6ERJ8t7FtX">DISCORD</a></div><p>© 2026 Odaris MC • Not affiliated with Mojang Studios or Microsoft.</p></footer>
 </main>
}