'use client';
import { useState } from 'react';
import { Copy, ShoppingCart, Sparkles, Shield, Zap, MessageCircle, Check, Menu, X, Users, BookOpen, HelpCircle, Crown } from 'lucide-react';

export default function Home(){
 const [copied,setCopied]=useState(false); const [menu,setMenu]=useState(false);
 const copy=()=>{navigator.clipboard?.writeText('zerithmc67.mcsh.io');setCopied(true);setTimeout(()=>setCopied(false),1500)};
 return <main>
  <nav className="nav"><a href="/" className="brand"><span className="cube">◆</span> ODARIS <b>MC</b><small>OFFICIAL MINECRAFT NETWORK</small></a><div className="links"><a href="/">Home</a><a href="/store">Store</a><a href="#why">About</a><a href="https://discord.gg/6ERJ8t7FtX">Discord</a></div><div className="nav-actions"><a className="google-button" href="/api/auth/google"><span>G</span> SIGN IN</a><a className="cart" href="/store">Store <ShoppingCart size={17}/></a><button className="menu-button" onClick={()=>setMenu(true)}><Menu/></button></div></nav>
  {menu&&<div className="drawer-backdrop" onClick={()=>setMenu(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><span>ODARIS MC</span><button onClick={()=>setMenu(false)}><X/></button></div><a href="/">HOME</a><a href="/store">STORE</a><a href="#why">ABOUT ODARIS MC</a><a href="https://discord.gg/6ERJ8t7FtX">DISCORD COMMUNITY</a><a href="/terms">TERMS & SERVER RULES</a><a href="/faq">FREQUENTLY ASKED QUESTIONS</a><a href="/admin">ADMIN CONSOLE</a><div className="drawer-sign"><a href="/api/auth/google">G&nbsp; PLAYER LOGIN / SIGN IN</a></div></aside></div>}
  <section className="hero"><div className="stars"/><div className="hero-inner"><div className="pill"><span/> NETWORK STATUS: ONLINE & OPERATIONAL</div><h1>WELCOME TO<br/><em>ODARIS MC</em></h1><p>The ultimate Minecraft survival experience featuring competitive gameplay, a player-driven economy, community events and a growing network.</p><div className="server-box"><span className="server-icon">🎮</span><div><small>SERVER ADDRESS • JAVA & BEDROCK</small><strong>zerithmc67.mcsh.io</strong></div><button onClick={copy}>{copied?<Check/>:<Copy/>}</button></div><div className="actions"><a className="primary" href="/store">EXPLORE STORE <ShoppingCart size={18}/></a><a className="discord-blue" href="https://discord.gg/6ERJ8t7FtX"><MessageCircle size={18}/> JOIN DISCORD</a></div></div></section>
  <section className="features" id="why"><div><Shield/><h3>FAIR PLAY</h3><p>Built around a fun and competitive community.</p></div><div><Sparkles/><h3>PREMIUM</h3><p>Optional cosmetics and perks for supporters.</p></div><div><Zap/><h3>FAST & RELIABLE</h3><p>Designed for a smooth multiplayer experience.</p></div><div><MessageCircle/><h3>COMMUNITY</h3><p>Get support and updates through Discord.</p></div></section>
  <section className="about-home"><div className="store-pill">ⓘ OUR NETWORK STORY & VISION</div><h2>ABOUT OUR <em>MINECRAFT NETWORK.</em></h2><p>Welcome to Odaris MC — a community-focused Minecraft network built for survival players, builders and PvP fans. Join the server, meet the community and build your legacy.</p><div className="stats"><div><strong>24/7</strong><span>COMMUNITY</span></div><div><strong>JAVA</strong><span>& BEDROCK</span></div><div><strong>100%</strong><span>COMMUNITY FOCUSED</span></div></div></section>
  <footer><div className="brand"><span className="cube">◆</span> ODARIS <b>MC</b></div><div className="footer-links"><a href="/store"><ShoppingCart/> Store</a><a href="https://discord.gg/6ERJ8t7FtX"><MessageCircle/> Discord</a><a href="/terms"><BookOpen/> Terms & Rules</a><a href="/faq"><HelpCircle/> FAQ</a><a href="/admin"><Crown/> Staff / Admin</a></div><p>© 2026 Odaris MC. Not affiliated with Mojang Studios or Microsoft.</p></footer>
 </main>
}
